# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:13
    container_name: pp-db-1
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hrmonitor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d hrmonitor"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8081:8080'
  web:
    build: .
    container_name: pp-web-1
    command: >
      sh -c "while ! pg_isready -h db -p 5432; do echo 'Waiting for db...'; sleep 2; done &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: